stages:
  - lint
  - build
  - test
  - dev deploy
  - prod deploy

image: ondrejsika/ci

variables:
  GIT_CLEAN_FLAGS: -ffdx -e node_modules/ -e .next/

  IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  IMAGE_TESTS: $CI_REGISTRY_IMAGE/tests:$CI_COMMIT_REF_SLUG

  KUBECONFIG: .kubeconfig

.lint:
  image: node
  stage: lint
  script:
    - yarn
    - yarn run prettier-check

.build:
  stage: build
  variables:
    COMPOSE_FILE: compose/main.yaml:compose/tests.yaml
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker-compose build
    - docker-compose push

tests:
  stage: test
  variables:
    COMPOSE_FILE: compose/main.yaml:compose/tests.yaml
    COMPOSE_PROJECT_NAME: $CI_JOB_ID
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker-compose run tests
  after_script:
    - docker-compose down
  only:
    changes:
      - yarn.lock
      - package.json
      - out
      - tests
      - Dockerfile
      - compose

.deploy template: &deploy_template
  script:
    - echo $KUBECONFIGFILE | base64 --decode > .kubeconfig
    - helm init --client-only
    - helm repo add ondrejsika https://helm.oxs.cz
    - helm upgrade --install $DEPLOY_NAME ondrejsika/simple-image --set image.repository=$CI_REGISTRY_IMAGE --set image.tag=$CI_COMMIT_REF_SLUG --set ingress.hosts={$DEPLOY_URL} --set replicaCount=1

.stop template: &stop_template
  script:
    - helm init -c
    - helm delete --purge $DEPLOY_NAME

dev deploy:
  <<: *deploy_template
  stage: dev deploy
  variables:
    DEPLOY_NAME: $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG
    DEPLOY_URL: $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG-188-166-195-72.nip.io
  environment:
    name: $CI_COMMIT_REF_SLUG
    url: https://$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG-188-166-195-72.nip.io
    on_stop: stop dev

stop dev:
  <<: *stop_template
  stage: dev deploy
  when: manual
  environment:
    name: $CI_COMMIT_REF_SLUG
    action: stop

dev deploy:
  <<: *deploy_template
  stage: dev deploy
  variables:
    DEPLOY_NAME: $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG
    DEPLOY_URL: $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG-188-166-195-72.nip.io
  environment:
    name: $CI_COMMIT_REF_SLUG
    url: https://$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG-188-166-195-72.nip.io
    on_stop: stop dev

stop dev:
  <<: *stop_template
  stage: dev deploy
  when: manual
  variables:
    DEPLOY_NAME: $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG
  environment:
    name: $CI_COMMIT_REF_SLUG
    action: stop

prod deploy:
  <<: *deploy_template
  stage: prod deploy
  when: manual
  variables:
    DEPLOY_NAME: $CI_PROJECT_PATH_SLUG
    DEPLOY_URL: prod-$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG-188-166-195-72.nip.io
  environment:
    name: $CI_PROJECT_PATH_SLUG
    url: https://prod-$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG-188-166-195-72.nip.io
    on_stop: stop prod
  only:
    - master

stop prod:
  <<: *stop_template
  stage: prod deploy
  when: manual
  variables:
    DEPLOY_NAME: $CI_PROJECT_PATH_SLUG
  environment:
    name: $CI_PROJECT_PATH_SLUG
    action: stop