stages:
  - lint
  - build
  - docker
  - dev deploy
  - prod deploy

variables:
  GIT_CLEAN_FLAGS: -ffdx -e node_modules/ -e .next/

lint:
  image: node
  stage: lint
  script:
    - yarn
    - yarn run prettier-check