stages:
  - lint
  - build
  - dev deploy
  - prod deploy

image: ondrejsika/ci

variables:
  GIT_CLEAN_FLAGS: -ffdx -e node_modules/ -e .next/

  IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

lint:
  image: node
  stage: lint
  script:
    - yarn
    - yarn run prettier-check

build:
  stage: build
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build $IMAGE .
    - docker push $IMAGE
